from datetime import datetime, timezone
from typing import Any, Dict, List
from uuid import uuid4

from app.models.hitl_case import (
    HITLCase,
    HITLCaseStatus,
)
from app.models.validation_result import (
    ValidationResult,
)


class HITLRoutingCapability:
    """
    Creates a HITL case from a deterministic validation result.

    Evidence generated by MatchingEngine is copied from
    ValidationException.evidence into HITLCase.evidence.
    """

    def route(
        self,
        validation_result: ValidationResult,
        evidence: List[Dict[str, Any]] | None = None,
    ) -> HITLCase | None:

        if validation_result.status != "EXCEPTION":
            return None

        if not validation_result.exceptions:
            return None

        # --------------------------------------------------
        # Collect evidence from ValidationExceptions
        # --------------------------------------------------

        collected_evidence = []

        for exception in validation_result.exceptions:
            if exception.evidence:
                collected_evidence.extend(
                    exception.evidence
                )

        # --------------------------------------------------
        # Also accept explicitly supplied evidence
        # --------------------------------------------------

        if evidence:
            collected_evidence.extend(evidence)

        # --------------------------------------------------
        # DEBUG CHECK
        # --------------------------------------------------

        print(
            "DEBUG ROUTER - collected evidence:",
            collected_evidence,
        )

        # --------------------------------------------------
        # Create HITL case
        # --------------------------------------------------

        hitl_case = HITLCase(
            case_id=(
                f"HITL-{uuid4().hex[:8].upper()}"
            ),
            status=HITLCaseStatus.PENDING,
            validation_result=validation_result,
            created_at=datetime.now(
                timezone.utc
            ),
        )

        # --------------------------------------------------
        # Explicit assignment AFTER construction
        # --------------------------------------------------

        hitl_case.evidence = list(
            collected_evidence
        )

        # --------------------------------------------------
        # DEBUG CHECK
        # --------------------------------------------------

        print(
            "DEBUG ROUTER - case evidence:",
            hitl_case.evidence,
        )

        return hitl_case